services:
  - type: web
    name: decentracert
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PINATA_JWT
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: SEPOLIA_API_URL
        sync: false 